// Mock data for the CreditIQ dashboard

export const userProfile = {
    name: "Arjun Sharma",
    avatar: "AS",
    creditScore: 742,
    previousScore: 718,
    scoreCategory: "Good",
    nextMilestone: 750,
    lastUpdated: "Feb 27, 2026",
};

export const creditCards = [
    {
        id: "hdfc_regalia",
        name: "HDFC Regalia Gold",
        bank: "HDFC Bank",
        brand: "mastercard",
        last4: "4382",
        colorStart: "#cf9f34",
        colorEnd: "#8c6b22",
        limit: 300000,
        used: 87000,
        color: "#f59e0b",
        icon: "💳",
        category: "Premium Rewards",
        dueDate: "Mar 15",
        statementDate: "Mar 1",
        apr: 3.5,
    },
    {
        id: "axis_ace",
        name: "Axis ACE",
        bank: "Axis Bank",
        brand: "visa",
        last4: "9011",
        colorStart: "#27272a",
        colorEnd: "#09090b",
        limit: 80000,
        used: 51000,
        color: "#8b5cf6",
        icon: "⚡",
        category: "Cashback",
        dueDate: "Mar 8",
        statementDate: "Mar 6",
        apr: 3.4,
    },
    {
        id: "sbi_simply",
        name: "SBI SimplyCLICK",
        bank: "SBI",
        brand: "visa",
        last4: "6552",
        colorStart: "#0284c7",
        colorEnd: "#0369a1",
        limit: 200000,
        used: 22000,
        color: "#0ea5e9",
        icon: "🌐",
        category: "Online Rewards",
        dueDate: "Mar 22",
        statementDate: "Mar 8",
        apr: 3.35,
    },
    {
        id: "icici_amazon",
        name: "Amazon ICICI",
        bank: "ICICI Bank",
        brand: "visa",
        last4: "2289",
        colorStart: "#3f3f46",
        colorEnd: "#18181b",
        limit: 100000,
        used: 64000,
        color: "#f97316",
        icon: "🛒",
        category: "Shopping",
        dueDate: "Mar 12",
        statementDate: "Feb 27",
        apr: 3.6,
    },
];

export const spendingData = [
    { month: "Sep", score: 698, utilization: 52 },
    { month: "Oct", score: 706, utilization: 48 },
    { month: "Nov", score: 712, utilization: 44 },
    { month: "Dec", score: 718, utilization: 41 },
    { month: "Jan", score: 728, utilization: 38 },
    { month: "Feb", score: 742, utilization: 30 },
];

export const categorySpending = [
    { category: "Dining", amount: 18500, percentage: 22, card: "HDFC Regalia", optimal: true },
    { category: "Travel", amount: 32000, percentage: 38, card: "Axis ACE", optimal: true },
    { category: "Shopping", amount: 14000, percentage: 17, card: "SBI SimplyCLICK", optimal: false },
    { category: "Groceries", amount: 8200, percentage: 10, card: "Amazon ICICI", optimal: true },
    { category: "Fuel", amount: 5500, percentage: 7, card: "HDFC Regalia", optimal: false },
    { category: "Entertainment", amount: 5200, percentage: 6, card: "Axis ACE", optimal: true },
];

export const scoreSimulations = [
    {
        action: "Pay ₹51,000 on Axis ACE",
        impact: +28,
        description: "Bring utilization from 64% → 29%",
        effort: "High",
        priority: 1,
    },
    {
        action: "Don't close SBI card",
        impact: +12,
        description: "Preserves 4 yrs credit history",
        effort: "Low",
        priority: 2,
    },
    {
        action: "Request limit on HDFC",
        impact: +18,
        description: "Reduces overall util. by 8%",
        effort: "Medium",
        priority: 3,
    },
    {
        action: "Pay ICICI before statement",
        impact: +9,
        description: "Show lower balance to bureaus",
        effort: "Medium",
        priority: 4,
    },
];

export const agentInsights = [
    {
        agent: "Utilization Agent",
        agentId: "utilization",
        icon: "📊",
        color: "#3b82f6",
        status: "alert",
        insight: "Axis ACE is at 64% utilization (₹51k/₹80k). Pay ₹51,000 before statement close to drop to 29% — the safe zone for a score boost of +20 to +30 pts.",
        priority: "critical",
        action: "Pay ₹51,000 on Axis ACE",
    },
    {
        agent: "Timing Agent",
        agentId: "timing",
        icon: "⏰",
        color: "#8b5cf6",
        status: "suggestion",
        insight: "Axis ACE statement closes in 2 days (Mar 6). Pay ₹51,000 NOW before close — bureaus will record the lower balance, maximizing your score gain.",
        priority: "high",
        action: "Act in 2 days",
    },
    {
        agent: "Rewards Agent",
        agentId: "rewards",
        icon: "🎁",
        color: "#10b981",
        status: "tip",
        insight: "You're spending on fuel with HDFC Regalia (1x points) but you're missing 5x points on SBI BPCL card.",
        priority: "medium",
        action: "Use SBI for fuel",
    },
    {
        agent: "Score Simulator",
        agentId: "simulator",
        icon: "🔮",
        color: "#f59e0b",
        status: "prediction",
        insight: "Paying ₹51,000 on Axis ACE projects a +20 to +30 pt gain. Score could hit 762–772 by Mar 31 — entering 'Very Good' tier.",
        priority: "high",
        action: "View simulation",
    },
    {
        agent: "Credit Coach",
        agentId: "coach",
        icon: "🎯",
        color: "#ec4899",
        status: "strategy",
        insight: "You're 8 points from 750. You qualify for HDFC Infinia upgrade. Trajectory: 780+ by June 2026.",
        priority: "medium",
        action: "See roadmap",
    },
];

export const paymentCalendar = [
    { date: "Feb 27", card: "Amazon ICICI", amount: 64000, type: "statement", urgent: true },
    { date: "Mar 1", card: "HDFC Regalia", amount: 87000, type: "statement", urgent: false },
    { date: "Mar 4", card: "Axis ACE", amount: 96000, type: "statement", urgent: false },
    { date: "Mar 8", card: "SBI SimplyCLICK", amount: 22000, type: "statement", urgent: false },
    { date: "Mar 12", card: "Amazon ICICI", amount: 64000, type: "due", urgent: false },
    { date: "Mar 15", card: "HDFC Regalia", amount: 87000, type: "due", urgent: false },
];

export const scoreRangeUnlocks = [
    { range: "300-579", label: "Poor", benefits: ["Basic secured cards"], color: "#ef4444", locked: false },
    { range: "580-669", label: "Fair", benefits: ["Standard credit cards"], color: "#f97316", locked: false },
    { range: "670-739", label: "Good", benefits: ["Most credit cards", "Home loan eligible"], color: "#f59e0b", locked: false },
    {
        range: "740-799",
        label: "Very Good",
        benefits: ["Premium credit cards", "Best loan rates"],
        color: "#10b981",
        locked: true,
        pointsNeeded: 8,
    },
    {
        range: "800-850",
        label: "Exceptional",
        benefits: ["Elite black cards", "Sub-7% home loans"],
        color: "#3b82f6",
        locked: true,
        pointsNeeded: 58,
    },
];
